# Generated by Django 4.2 on 2023-06-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0021_datosactivity_icon'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuarios',
            name='actividades_favoritas',
            field=models.ManyToManyField(blank=True, to='actividades.activity'),
        ),
    ]
