# Generated by Django 4.2 on 2023-06-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_datosusuarios_actividades_favoritas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosusuarios',
            name='actividades_favoritas',
        ),
    ]
