# Generated by Django 4.0 on 2026-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuarios',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datosusuarios',
            name='limitaciones',
            field=models.CharField(blank=True, help_text='Ej: problemas de rodilla, alergia al frío, no puede correr', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datosusuarios',
            name='nivel_experiencia',
            field=models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='datosusuarios',
            name='objetivos',
            field=models.CharField(blank=True, help_text='Ej: pérdida de peso, ganar músculo, mejorar resistencia, socializar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datosusuarios',
            name='preferencia_formato',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('grupal', 'Grupal'), ('sin_preferencia', 'Sin preferencia')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='datosusuarios',
            name='preferencias_tipo',
            field=models.CharField(blank=True, help_text='Tipos de actividades preferidas: musculacion, cardio, mente-cuerpo, raqueta, acuatico, funcional', max_length=255, null=True),
        ),
    ]
