# Generated by Django 4.2 on 2023-05-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_datosactivity_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='status',
            new_name='reservar',
        ),
    ]
