# Generated by Django 4.2 on 2023-05-05 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_alter_datosactivity_day_alter_datosactivity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosactivity',
            name='day',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, unique=True),
        ),
    ]
