# Generated by Django 4.2 on 2023-05-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_alter_datosactivity_day_alter_datosactivity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosactivity',
            name='time',
            field=models.CharField(choices=[('1', '9.00hs - 10.00hs'), ('2', '10.00hs - 11.00hs'), ('3', '11.00hs - 12.00hs'), ('4', '12.00hs - 13.00hs'), ('5', '13.00hs - 14.00hs'), ('6', '14.00hs - 15.00hs'), ('7', '15.00hs - 16.00hs'), ('8', '16.00hs - 17.00hs'), ('9', '17.00hs - 18.00hs'), ('10', '18.00hs - 19.00hs'), ('11', '19.00hs - 20.00hs'), ('12', '20.00hs - 21.00hs'), ('13', '21.00hs - 22.00hs')], default='1', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='datosactivity',
            unique_together={('id_act', 'time', 'day')},
        ),
    ]
