# Generated by Django 4.2 on 2023-05-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_alter_datosactivity_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
