# Generated by Django 4.2 on 2023-05-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_activity_aire_libre'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosactivity',
            name='condiciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datosactivity',
            name='temperatura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
