# Generated by Django 4.2 on 2023-05-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_rename_temperatura_actual_datosactivity_temperatura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosactivity',
            old_name='temperatura',
            new_name='temperatura_max',
        ),
        migrations.AddField(
            model_name='datosactivity',
            name='temperatura_min',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
