# Generated by Django 4.2 on 2023-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_rename_temperatura_datosactivity_temperatura_max_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datosactivity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='datosactivity',
            name='end_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='datosactivity',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterUniqueTogether(
            name='datosactivity',
            unique_together={('id_act', 'day', 'start_time', 'end_time')},
        ),
        migrations.RemoveField(
            model_name='datosactivity',
            name='time',
        ),
    ]
