# Generated by Django 4.2 on 2023-05-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0014_alter_datosactivity_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosactivity',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosactivity',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
    ]
