# Generated by Django 4.2 on 2023-05-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0015_alter_datosactivity_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosactivity',
            name='end_time',
            field=models.TimeField(default='00:01'),
        ),
        migrations.AlterField(
            model_name='datosactivity',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
