# Generated by Django 4.2 on 2023-06-01 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actividades', '0017_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('usuario_id', 'datos_activity')},
        ),
    ]
