# Generated by Django 4.2 on 2023-06-01 20:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actividades', '0018_rename_usuario_reserva_usuario_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('usuario', 'datos_activity')},
        ),
    ]
