# Generated by Django 4.2 on 2023-06-09 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('actividades', '0019_rename_usuario_id_reserva_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.datosusuarios'),
        ),
    ]
