# Generated by Django 4.2 on 2023-06-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0020_alter_reserva_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosactivity',
            name='icon',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
