# Generated by Django 4.2 on 2023-06-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0023_mensaje_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='leido',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='nuevo',
            field=models.BooleanField(default=True),
        ),
    ]
