# Generated by Django 4.2 on 2023-06-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0024_remove_mensaje_leido_mensaje_nuevo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='nuevo',
        ),
    ]
