# Generated by Django 4.2 on 2023-06-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0027_alter_mensaje_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
